### ISSUE TITLE
Bug in frame.c when setting cycletime

### ISSUE THREAD

**Issue by lecouteux** [openv/vcontrold#22] opened 2018-01-03 11:24 UTC
Using the master branche : 
vctrld>setIntervalleLundiChauffage 06:00 22:00
ERR: >FRAMER: addr was still active FE06
>FRAMER: Command send
>FRAMER: unexpected length 8 08
Fehler recv, Abbruch
Fehler beim ausfuehren von setIntervalleLundiChauffage 06:00 22:00

And for vcontrold : 

[vcontrold.xml.txt](https://github.com/openv/vcontrold/files/1600155/vcontrold.xml.txt)
[vito.xml.txt](https://github.com/openv/vcontrold/files/1600156/vito.xml.txt)
[31602] Wed Jan  3 12:17:54 2018 : TCP socket 3002 geoeffnet
[31602] Wed Jan  3 12:18:08 2018 : Client verbunden 192.168.1.108:33488 (FD:5)
[31602] Wed Jan  3 12:18:17 2018 : Befehl: setIntervalleLundiChauffage 06:00 22:00
[31602] Wed Jan  3 12:18:17 2018 : Process 31602 tries to aquire lock
[31602] Wed Jan  3 12:18:17 2018 : Process 31602 got lock
[31602] Wed Jan  3 12:18:17 2018 : >FRAMER: open device /dev/ttyAMA0 ProtocolID 41
[31602] Wed Jan  3 12:18:17 2018 : konfiguriere serielle Schnittstelle /dev/ttyAMA0
[31602] Wed Jan  3 12:18:17 2018 : >SEND: 04
[31602] Wed Jan  3 12:18:17 2018 : <RECV: len=1 06 (10.0 ms)
[31602] Wed Jan  3 12:18:17 2018 : <RECV: received 06
[31602] Wed Jan  3 12:18:17 2018 : >FRAMER: closed
[31602] Wed Jan  3 12:18:17 2018 : >SEND: 16
[31602] Wed Jan  3 12:18:17 2018 : >SEND: 00
[31602] Wed Jan  3 12:18:17 2018 : >SEND: 00
[31602] Wed Jan  3 12:18:19 2018 : <RECV: len=1 05 (1980.0 ms)
[31602] Wed Jan  3 12:18:19 2018 : <RECV: received 05
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 16
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 00
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 00
[31602] Wed Jan  3 12:18:19 2018 : <RECV: len=1 06 (20.0 ms)
[31602] Wed Jan  3 12:18:19 2018 : <RECV: received 06
[31602] Wed Jan  3 12:18:19 2018 : >FRAMER: opened
[31602] Wed Jan  3 12:18:19 2018 : Cycle Time: 06:00 -> [30]
[31602] Wed Jan  3 12:18:19 2018 : Cycle Time: 22:00 -> [B0]
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 41
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 0D
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 00
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 02
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 20
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 00
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 08
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 30
[31602] Wed Jan  3 12:18:19 2018 : >SEND: B0
[31602] Wed Jan  3 12:18:19 2018 : >SEND: FF
[31602] Wed Jan  3 12:18:19 2018 : >SEND: FF
[31602] Wed Jan  3 12:18:19 2018 : >SEND: FF
[31602] Wed Jan  3 12:18:19 2018 : >SEND: FF
[31602] Wed Jan  3 12:18:19 2018 : >SEND: FF
[31602] Wed Jan  3 12:18:19 2018 : >SEND: FF
[31602] Wed Jan  3 12:18:19 2018 : >SEND: 11
[31602] Wed Jan  3 12:18:19 2018 : <RECV: len=1 06 (70.0 ms)
[31602] Wed Jan  3 12:18:19 2018 : <RECV: received 06
[31602] Wed Jan  3 12:18:19 2018 : >FRAMER: addr was still active FE06
[31602] Wed Jan  3 12:18:19 2018 : >FRAMER: Command send
[31602] Wed Jan  3 12:18:19 2018 : >FRAMER: no preset result
[31602] Wed Jan  3 12:18:19 2018 : <RECV: len=1 41 (0.0 ms)
[31602] Wed Jan  3 12:18:19 2018 : <RECV: received 41
[31602] Wed Jan  3 12:18:19 2018 : <RECV: len=1 05 (0.0 ms)
[31602] Wed Jan  3 12:18:19 2018 : <RECV: received 05
[31602] Wed Jan  3 12:18:19 2018 : <RECV: len=5 01 (0.0 ms)
[31602] Wed Jan  3 12:18:19 2018 : <RECV: len=1 30 (10.0 ms)
[31602] Wed Jan  3 12:18:19 2018 : <RECV: received 01 02 20 00 08 30
[31602] Wed Jan  3 12:18:19 2018 : >FRAMER: unexpected length 8 08
[31602] Wed Jan  3 12:18:19 2018 : Fehler recv, Abbruch
[31602] Wed Jan  3 12:18:19 2018 : Fehler beim ausfuehren von setIntervalleLundiChauffage 06:00 22:00

**Comment by speters** [comment] 2018-01-03 13:16
You seem to be running an outdated version of `vcontrold`. Updated versions have a fix in the framer code.

Please make sure you are using the **latest** **version** (HEAD) from the `vcontrold` master branch or at least the latest [release](https://github.com/openv/vcontrold/releases).

If you are still running into this issue with the latest version, please reopen this issue.

**Comment by speters** [comment] 2018-01-03 20:36
duplicate of https://github.com/openv/vcontrold/issues/23

**Comment by speters** [comment] 2018-01-05 15:05
Mr6 for confirming this with an up-to-date version, and thx again for your french translation in the config files.

https://github.com/openv/vcontrold/pull/25 is my proposal for a fix to this issue.

**Comment by speters** [comment] 2018-01-20 16:03
Fixed by https://github.com/openv/vcontrold/pull/25

**Closed by speters** 2018-01-20 16:03 UTC
Labels: duplicate
